### ISSUE TITLE
ODE?

### ISSUE THREAD

**Issue by andreiw** [slp/osfmk-mklinux#1]
Hiya, just a quick question - where did you get the ODE tools (i.e. "build")?

**Comment by slp** [comment]
Some time ago, an src.rpm package named ode4linux could be found around the web, which contained the GNU/Linux port of the ODE tools.

I've just tried googling it, and there were no results. This is probably due to the fact that the MkLinux site is no longer available.

I should have a copy of that package somewhere. If you're interested, I can do a quick search and upload it to some place.

**Comment by andreiw** [comment]
Please... If you find them I think it would be a great service for everybody interested in tinkering with the MkLinux sources.

Even the pre-Linux ODE tools are hard to find. I've had no luck with ode4linux.

**Comment by slp** [comment]
I've also lost my local copy. Luckily, I was able to find the SRC.RPM on a MkLinux FTP mirror:

ftp://ftp.u-aizu.ac.jp/pub/os/Linux/mklinux/mklinux-pre-R1/SRPMS/SRPMS/ode-2.3.4-5f.src.rpm

That contains ode4linux, some patches, and an RPM spec file (which you can use as reference for building the software). When I find some time, I'll create another repository with a clean copy of the ODE code, so it won't get lost again.

By the way, the easiest way for getting a working build environment for MkLinux, is running an old GNU/Linux distro on a virtual machine. I've used Debian Woody, which provides GCC versions 2.95 and 2.72, required for building OSFMk and the specialized Linux kernel, respectively.

Good luck!

**Comment by andreiw** [comment]
Wow. Cool. Thanks a lot. Ok I've a repo setup and it builds with GCC 4.8.

https://github.com/andreiw/ode4linux

I didn't try on PPC yet.
